src/OnlinyBook/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using OnlinyBook.Service.Common.Exceptions;
using OnlinyBook.Service.Common.Helpers;
using OnlinyBook.Service.Dtos.Accounts;
using OnlinyBook.Service.Dtos.Users;
using OnlinyBook.Service.Intefaces.Accounts;
using OnlinyBook.Service.Intefaces.Users;

namespace OnlinyBook.Controllers
{
	[Route("account")]
	public class AccountController : Controller
	{
		private readonly IAccountService _service;
		private readonly IUserService _userService;
		public AccountController(IAccountService acccountService, IUserService userService)
		{
			this._service = acccountService;
			this._userService = userService;
		}
		[HttpGet("login")]
		public ViewResult Login()
		{
			return View("Login");
		}

		[HttpPost("login")]
		public async Task<IActionResult> LoginAsync(AccountLoginDto accountLoginDto)
		{
			if (ModelState.IsValid)
			{
				try
				{
					string token = await _service.LoginAsync(accountLoginDto);
					HttpContext.Response.Cookies.Append("X-Access-Token", token, new CookieOptions()
					{
						HttpOnly = true,
						SameSite = SameSiteMode.Strict
					});
					return RedirectToAction("Index", "Home", new { area = "" });
				}
				catch (ModelErrorException modelError)
				{
					ModelState.AddModelError(modelError.Property, modelError.Message);
					return Login();
				}
			}
			else return Login();
		}

		[HttpGet("register")]
		public ViewResult Register()
		{
			return View("Register");
		}

		[HttpPost("register")]
		public async Task<IActionResult> RegisterAsync(AccountRegisterDto accountRegisterDto)
		{
			if (ModelState.IsValid)
			{
				bool result = await _service.RegisterAsync(accountRegisterDto);
				if (result)
					return RedirectToAction("login", "account", new { area = "" });
				else
					return Register();
			}
			else return Register();
		}

		[HttpGet("logout")]
		public IActionResult LogOut()
		{
			HttpContext.Response.Cookies.Append("X-Access-Token", "", new CookieOptions()
			{
				Expires = TimeHelper.GetCurrentServerTime().AddDays(-1)
			});
			return RedirectToAction("Index", "Home", new { area = "" });
		}

		[HttpGet("upaccount")]
		public async Task<ViewResult> UpAccount()
		{
			var user = await _userService.GetAsync(HttpContextHelper.UserId);
			var userUpdate = new UserUpdateDto()
			{
				FirstName = user.FirstName,
				LastName = user.LastName,
				Email = user.Email,
				ImagePath = user.ImagePath,
				PhoneNumber = user.PhoneNumber,
			};
			return View("../Account/upaccount", userUpdate);
		}

		[HttpPost("upaccount")]
		public async Task<IActionResult> UpdateAsync([FromForm] UserUpdateDto userUpdateDto)
		{
			if (ModelState.IsValid)
			{
				bool result = await _service.UpdateAsync(HttpContextHelper.UserId, userUpdateDto);
				if (result)
					return RedirectToAction("Index", "Home", new { area = "" });
				else
					return RedirectToAction("upaccount", "Account", new { area = "" });
			}
			else return RedirectToAction("upaccount", "Account", new { area = "" });
		}
	}
}

src/OnlinyBook/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using OnlinyBook.Service.ViewModels.Contacts;

namespace OnlinyBook.Controllers
{
	public class ContactsController : Controller
	{
		public IActionResult Index() //contacts
		{
			return View();
		}

		[HttpPost]
		public IActionResult Check(ContactViewModel contact) //contacts
		{
			if (ModelState.IsValid)
			{
				return Redirect("/");
			}
			return View("Index");
		}
	}
}

src/OnlinyBook/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlinyBook.Models;
using System.Diagnostics;

namespace OnlinyBook.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

src/OnlinyBook/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using OnlinyBook.Service.Common.Unils;
using OnlinyBook.Service.Intefaces.Orders;

namespace OnlinyBook.Controllers
{
	[Route("orders")]
	public class OrderController : Controller
	{
		private readonly IOrderService _orderService;
		private readonly int _pageSize = 30;

		public OrderController(IOrderService orderService)
		{
			this._orderService = orderService;
		}
		public async Task<IActionResult> Index(int page = 1)
		{
			var products = await _orderService.GetAllAsync(new PaginationParams(page, _pageSize));
			return View("Index", products);
		}

	}
}

src/OnlinyBook/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using OnlinyBook.Service.Common.Helpers;
using OnlinyBook.Service.Common.Unils;
using OnlinyBook.Service.Dtos.Orders;
using OnlinyBook.Service.Intefaces.Orders;
using OnlinyBook.Service.Intefaces.Products;

namespace OnlinyBook.Controllers
{
	[Route("products")]
	public class ProductsController : Controller
	{
		private readonly IOrderService _orderService;
		private readonly IProductService _productService;
		private readonly int _pageSize = 2;

		public ProductsController(IProductService productService, IOrderService orderService)
		{
			this._productService = productService;
			this._orderService = orderService;
		}
		public async Task<IActionResult> Index(int page = 1)
		{
			var products = await _productService.GetAllAsync(new PaginationParams(page, _pageSize));
			return View("Index", products);
		}
		[HttpGet("get")]
		public async Task<ViewResult> GetAsync(int productId)
		{
			var product = await _productService.GetAsync(productId);
			var dto = new OrderCreateDto()
			{
				UserId = HttpContextHelper.UserId,
				ProductId = productId,
				Description = product.Description,
				ImagePath = product.ImagePath,
				Name = product.Name,
				Price = product.Price,
			};

			if (product is not null)
			{
				await _orderService.CreateAsync(dto);

			}
			return View(product);
		}

		[HttpGet("down")]
        public FileResult DownloadFile(string fileName)
        {
			//Build the File Path.
			string path = "wwwroot/files/" + fileName;

            //Read the File data into Byte Array.
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the File to Download.
            return File(bytes, "application/octet-stream", fileName);
        }
    }
}

src/OnlinyBook/ViewComponents/IdentityViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlinyBook.Service.Intefaces.Common;
using OnlinyBook.Service.ViewModels.Accounts;

namespace OnlinyBook.ViewComponents
{
	public class IdentityViewComponent : ViewComponent
	{
		private readonly IIdentityService _identityService;
		public IdentityViewComponent(IIdentityService identity)
		{
			this._identityService = identity;
		}
		public IViewComponentResult Invoke()
		{
			AccountBaseViewModel accountBaseViewModel = new AccountBaseViewModel()
			{
				Id = _identityService.Id!.Value,
				Email = _identityService.Email,
				FirstName = _identityService.FirstName,
				LastName = _identityService.LastName,
				ImagePath = _identityService.ImagePath,
				Money = _identityService.Money

			};
			return View(accountBaseViewModel);
		}
	}

}

src/OnlinyBook/Views/Contacts/Index.cshtml
@using OnlinyBook.Service.ViewModels.Contacts;
@model ContactViewModel
@{
    ViewData["Title"] = "Обратная связь";
}
<div class="card w-250px h-300">
    <div class="mt-5 mb-5 mx-5">
        <h1>Обратная связь</h1>
        
        <form method="post" asp-controller="Contacts" asp-action="Check">
                
                <label asp-for="Email"></label>
                <input asp-for="Email"/>
                <span asp-validation-for="Email"></span>
        
                <label asp-for="Message"></label>
                <input asp-for="Message"/>
                <span asp-validation-for="Message"></span>
        
                <div>
                    <button class="btn btn-success">Отправить</button>
                </div>
        </form>
    </div>
</div>

src/OnlinyBook/Views/Home/Index.cshtml
@using OnlinyBook.Service.ViewModels.Products;
@model ProductViewModel
@{
    ViewData["Title"] = "Главная страница сайта";
}


<h1>Главная страница сайта</h1>

src/OnlinyBook/Views/Order/Index.cshtml
@using OnlinyBook.Service.Common.Helpers;
@using OnlinyBook.Service.Common.Unils;
@using OnlinyBook.Service.ViewModels.Orders;
@model PagedList<OrderBaseViewModel>

@{
    ViewData["Title"] = "Покупки";
}

<div>
    @{
        foreach (var product in Model)
        {
            <div class="card w-250px h-300">
                <div class="mt-5 mb-5 mx-5">
                    <div class="item">
                        <div class="d-flex align-items-stretch">
                            <div class="me-4">
                                <img src="~/@product.ImagePath" alt="" width="150" height="200">
                            </div>
                            <span>@product.Description</span>
                        </div>

                        <div class="symbol symbol-50px me-5">
                            <span class="fs-5" fw-bold text-gray-600>Название книги: @product.Name</span>
                        </div>

                        <div class="symbol symbol-50px me-5">
                            <span>Цена: @product.Price сум</span>
                        </div>

                    </div>
                </div>
            </div>
        }

        //<ul class="pagination">
        //    @{
        //        string pale = "<";
        //        if (Model.MetaData.HasPrevious)
        //        {
        //            <li class="page-item previous m-1">
        //                <a asp-controller="products" asp-action="Index" asp-route-page="@(Model.MetaData.CurrentPage-1)" class="page-link">
        //                    <i class="previous">@pale</i>
        //                </a>
        //            </li>
        //        }
        //        else
        //        {
        //            <li class="page-item previous disabled m-1">
        //                <a href="#" class="page-link">
        //                    <i class="previous">@pale</i>
        //                </a>
        //            </li>
        //        }


        //        for (int _page = 1; _page <= Model.MetaData.TotalPages; _page++)
        //        {
        //            if (Model.MetaData.TotalPages >= 5)
        //            {
        //                if (Model.MetaData.CurrentPage - 1 == _page || Model.MetaData.CurrentPage == _page || Model.MetaData.CurrentPage + 1 == _page || _page == 1 || _page == Model.MetaData.TotalPages)
        //                {
        //                    if (_page == Model.MetaData.CurrentPage)
        //                    {
        //                        <li class="page-item active m-1">
        //                            <a asp-controller="products" asp-action="Index" asp-route-page="@_page" class="page-link">@_page</a>
        //                        </li>
        //                    }
        //                    else
        //                    {
        //                        <li class="page-item m-1">
        //                            <a asp-controller="products" asp-action="Index" asp-route-page="@_page" class="page-link">@_page</a>
        //                        </li>
        //                    }
        //                }
        //                else if (Model.MetaData.CurrentPage + 2 == _page || Model.MetaData.CurrentPage - 2 == _page)
        //                {
        //                    if (Model.MetaData.TotalPages != Model.MetaData.CurrentPage + 2)
        //                    {
        //                        <li class="page-item m-1">
        //                            <a class="page-link">...</a>
        //                        </li>
        //                    }
        //                }

        //            }
        //            else
        //            {
        //                if (_page == Model.MetaData.CurrentPage)
        //                {
        //                    <li class="page-item active m-1">
        //                        <a asp-controller="products" asp-action="Index" asp-route-page="@_page" class="page-link">@_page</a>
        //                    </li>
        //                }
        //                else
        //                {
        //                    <li class="page-item m-1">
        //                        <a asp-controller="products" asp-action="Index" asp-route-page="@_page" class="page-link">@_page</a>
        //                    </li>
        //                }
        //            }

        //        }

        //        if (Model.MetaData.HasNext)
        //        {
        //            <li class="page-item next m-1">
        //                <a asp-controller="products" asp-action="Index" asp-route-page="@(Model.MetaData.CurrentPage+1)" class="page-link">
        //                    <i class="next">></i>
        //                </a>
        //            </li>
        //        }
        //        else
        //        {
        //            <li class="page-item disabled next m-1">
        //                <a href="#" class="page-link">
        //                    <i class="next">></i>
        //                </a>
        //            </li>
        //        }
        //    }
        //</ul>

    }

</div>

src/OnlinyBook/Views/Products/Get.cshtml
@using OnlinyBook.Service.ViewModels.Products;
@model ProductViewModel

<div class="d-flex flex-row">
    <div class="row-cols-2">
        <img class="w-300px h-300px card-rounded" src="~/@Model.ImagePath" alt="@Model.Name" />
    </div>
    <div class="row-cols-2 mx-10 bg-white w-50 h-100">
        <table class="table mb-3">
            <thead>
                <tr class="fw-bolder text-gray-700 fs-5 text-end">
                    <td class="d-flex align-items-center pt-6">
                        <i class="fa fa-genderless text-danger fs-2 me-2"></i>Цена :
                    </td>
                    <td class="pt-6 text-dark fw-boldest">
                        @Model.Price
                    </td>
                </tr>
                
            </thead>
        </table>
        <div class="mb-4 me-4 ms-4 mt-4">
            <a asp-controller="products" asp-action="down" asp-route-fileName="@Model.ProductsPath" class="btn btn-outline-success">Скачать</a>
        </div>
    </div>
</div>

src/OnlinyBook/Views/Products/Index.cshtml
@using OnlinyBook.Service.Common.Helpers;
@using OnlinyBook.Service.Common.Unils;
@using OnlinyBook.Service.ViewModels.Products;
@model PagedList<ProductBaseViewModel>

@{
    ViewData["Title"] = "Продукт";
}

<div>
    @{
        foreach(var product in Model)
        {
            <div class="card w-250px h-300">
                <div class="mt-5 mb-5 mx-5">
                    <div class="item">
                        <div class="d-flex align-items-stretch">
                            <div class="me-4">
                                <img src="~/@product.ImagePath" alt="" width="150" height="200">
                            </div>
                            <span>@product.Description</span>
                        </div>

                        <div class="symbol symbol-50px me-5">
                            <span class="fs-5" fw-bold text-gray-600>Название книги: @product.Name</span>
                        </div>

                        <div class="symbol symbol-50px me-5">
                            <span>Цена: @product.Price сум</span>
                        </div>

                        @{
                            if (HttpContextHelper.UserId != 0)
                            {
                                if (HttpContextHelper.UserMoney >= product.Price)
                                {
                                    <a asp-controller="products" asp-action="get" asp-route-productId="@product.Id" class="btn btn-success">Заказать</a>
                                }
                                else
                                {
                                    <a class="btn btn-success" data-bs-toggle="modal" data-bs-target="#kt_modal_1" role="dialog">Заказать</a>
                                    <div class="modal fade" tabindex="-1" id="kt_modal_1">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h3 class="modal-title">Ошибка</h3>

                                                    <!--begin::Close-->
                                                    <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                                                        <span class="svg-icon svg-icon-1"></span>
                                                    </div>
                                                    <!--end::Close-->
                                                </div>

                                                <div class="modal-body">
                                                    <p>У вас не хватает денег</p>
                                                </div>

                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">Закрыть</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }
                            else
                            {
                                <div class="symbol symbol-50px me-5">
                                    <a asp-controller="Account" asp-action="login" class="btn btn-success">Заказать</a>
                                </div>
                            }
                        }
                        
                    </div>
                </div>
            </div>
        }

        <ul class="pagination">
            @{
                string pale = "<";
                if (Model.MetaData.HasPrevious)
                {
                    <li class="page-item previous m-1">
                        <a asp-controller="products" asp-action="Index" asp-route-page="@(Model.MetaData.CurrentPage-1)" class="page-link">
                            <i class="previous">@pale</i>
                        </a>
                    </li>
                }
                else
                {
                    <li class="page-item previous disabled m-1">
                        <a href="#" class="page-link">
                            <i class="previous">@pale</i>
                        </a>
                    </li>
                }


                for(int _page = 1; _page <= Model.MetaData.TotalPages; _page++)
                {
                    if(Model.MetaData.TotalPages >= 5)
                    {
                        if (Model.MetaData.CurrentPage - 1 == _page || Model.MetaData.CurrentPage == _page || Model.MetaData.CurrentPage + 1 == _page || _page == 1 || _page== Model.MetaData.TotalPages)
                        {
                            if (_page == Model.MetaData.CurrentPage)
                            {
                                <li class="page-item active m-1">
                                    <a asp-controller="products" asp-action="Index" asp-route-page="@_page" class="page-link">@_page</a>
                                </li>
                            }
                            else
                            {
                                <li class="page-item m-1">
                                    <a asp-controller="products" asp-action="Index" asp-route-page="@_page" class="page-link">@_page</a>
                                </li>
                            }
                        }
                        else if (Model.MetaData.CurrentPage + 2 == _page || Model.MetaData.CurrentPage - 2 == _page)
                        {
                            if (Model.MetaData.TotalPages != Model.MetaData.CurrentPage + 2)
                            {
                                <li class="page-item m-1">
                                    <a class="page-link">...</a>
                                </li>
                            }
                        }
                        
                    }
                    else
                    {
                        if(_page == Model.MetaData.CurrentPage)
                        {
                            <li class="page-item active m-1">
                                <a asp-controller="products" asp-action="Index" asp-route-page="@_page" class="page-link">@_page</a>
                            </li>
                        }
                        else
                        {
                            <li class="page-item m-1">
                                <a asp-controller="products" asp-action="Index" asp-route-page="@_page" class="page-link">@_page</a>
                            </li>
                        }
                    }

                }

                if (Model.MetaData.HasNext)
                {
                    <li class="page-item next m-1">
                        <a asp-controller="products" asp-action="Index" asp-route-page="@(Model.MetaData.CurrentPage+1)" class="page-link">
                            <i class="next">></i>
                        </a>
                    </li>
                }
                else
                {
                    <li class="page-item disabled next m-1">
                        <a href="#" class="page-link">
                            <i class="next">></i>
                        </a>
                    </li>
                }
            }
        </ul>

    }

</div>

src/OnlinyBook/Views/Shared/_Layout.cshtml
@using OnlinyBook.Service.Common.Helpers;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlinyBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlinyBook.styles.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <span class="logo">Online Book</span>
        <div class="d-flex bd-highlight">
            <div class="p-2 flex-grow-1 bd-highlight">
                <a asp-controller="Home" asp-action="Index" type="submit" class="btn btn-light">Главная</a>
                <a asp-controller="products" asp-action="Index" type="submit" class="btn btn-light">Продукт</a>
                <a asp-controller="contacts" asp-action="Index" type="submit" class="btn btn-light">Обратная связь</a>
            </div>
            @{

                if (HttpContextHelper.UserId != 0)
                {
                    <div class="p-2 bd-highlight">
                        <a asp-controller="Order" asp-action="Index" type="submit" class="btn btn-light">Покупки</a>
                    </div>

                    <div class="bd-highlight">
                        @await Component.InvokeAsync("Identity")
                    </div>
                }
                else
                {
                    <div class="p-2 bd-highlight">
                        <a asp-controller="account" asp-action="register" type="submit" class="btn btn-light">Регистрация</a>
                    </div>
                    <div class="p-2 bd-highlight">
                        <a asp-controller="account" asp-action="login" type="submit" class="btn btn-light">Вход</a>
                    </div>
                }
            }
        </div>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>Все права зашишены</footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/plugins.site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>